### ISSUE TITLE
Encoding using multiple GPUs

### ISSUE THREAD

**Issue by MathiasStokholm** [CESNET/GPUJPEG#1]
Hi and thanks for this awesome project.

Is there any way to do encoding on two GPUs simultaneously? I have a use case where I need to compress data to jpeg as quickly as possible, and using just a single GPU has turned out to be too slow (at least in my preliminary tests). I'm feeding images to GPUJPEG through a queue, so I would ideally like to have two threads, each with its own GPUJPEG encoder, grabbing data from the queue, then compressing and writing the image to disk.

**Comment by MartinPulec** [comment]
Hi Mathias,

quick answer - it depends. You mean using 2 GPUs for one image or 2 
images? It is definitely possible if you allocate gpujpeg encoders for 
different cards in different threads (just don't do this for one card - 
there are some global variables, this is fixed in git branch 
decode-gltex). For one image it won't be possible for now.


Regards,
Martin Pulec

**Comment by MathiasStokholm** [comment]
@MartinPulec I would be doing one image per thread. Thanks for your answer! Does `decode-gltex` have less global shared state then?

**Comment by MartinPulec** [comment]
decode-gltex is generally improved version, however not yet merged - it 
is not so tested and there are small changes in API. The thing I 
mentioned is that decode-gltex avoids global variables at all. However, 
it doesn't hurt for master branch either, unless you use one card 
concurrently from within multiple threads. It is because the global 
variables there are the GPU ones and CUDA creates every (global) device 
variable for every cards in system. Therefore, using GPUJPEG instances 
even from master branch in 2 threads is safe provided you use 2 cards.

Regards,
Martin Pulec

**Comment by MathiasStokholm** [comment]
@MartinPulec That sounds great. I will try encoding using two threads with an encoder each then. Is there any performance improvements included in `decode-gltex`?

**Comment by MartinPulec** [comment]
Good question - as far as I know not much, there are mainly functional 
improvements. However, they can be used to improve perfomance - things 
like CUDA streams, use of different on-GPU buffers (CUDA, OpenGL) etc. 
But you wouldn't profit from them unless you don't use them. However, I 
am not 100% sure whether there isn't any improvement at all, colleagues 
from a partner company have written that, so you may check.


Martin

**Comment by MathiasStokholm** [comment]
Thanks for all your thorough answers, you can close this now :+1:
