### ISSUE TITLE
Fail to pre-allocate encoding

### ISSUE THREAD

**Issue by liuzhenzhonguai** [CESNET/GPUJPEG#10]
I am using GPUJPEG do image compress.
 I will compress many different size of RGB images and I found I have to call the method gpujpeg_encoder_allocate every time before I compress one image, otherwise it will be failed for the second time.
I call as the following code:

	gpujpeg_encoder_input encoder_input;
	gpujpeg_encoder_input_set_image(&encoder_input, pImageInput);

	uint8_t* image_compressed = NULL;
	int image_compressed_size = 0;
				
	gpujpeg_encoder_allocate(m_jpegEncoder, &param, &param_image, GPUJPEG_ENCODER_INPUT_IMAGE , 16);
	if ( gpujpeg_encoder_encode(m_jpegEncoder,&param, &param_image, &encoder_input, &image_compressed, 
		&image_compressed_size) != 0 )
	{
		
		return;
	}

the program working well.
But it often print some error message in console
[GPUJPEG][Error] ..\src\gpujpeg_common.cpp (line 844): Coder component copy: in valid argument.
[GPUJPEG][Error] Fail to pre-allocate encoding!

also the program is working well. But i want to know the reason for print the error. And I think if has no such error, the program will run more fast.

Anybody can tell me the reason?
Thanks!

**Comment by MartinPulec** [comment]
Hi,

would it be possible for you to provide a minimal working example for the problems? And check if it is sensitive to the content of the images. I tried to check your first problem (the need to call gpujpeg_encoder_allocate()) but i haven't been able to reproduce it. (I was using this code [test.cpp.txt](https://github.com/CESNET/GPUJPEG/files/2206040/test.cpp.txt), can you please try it to check whether the problem isn't HW-dependent?) I didn't check the second the second problem yet since the call of gpujpeg_encoder_allocate() was not needed for me.

Thanks!
Martin

**Comment by liuzhenzhonguai** [comment]
thank for you code, your code is work well in my computer. 
And I try to find the difference, and I find every time I compress one image, I will call the method gpujpeg_image_destroy(compressed); but your code not call , so I remove the code inside for me, It is work ok now.
do we need free the compressed char at last?

**Comment by MartinPulec** [comment]
Yep, you are right, that may be it. It is possibly not entirely clear but the encoded image should not be destroyed because it is hold by the encoder. And as far as I know, it doesn't need to be destroyed in the end, either (I've just recheck it with valgrind).

Martin
