### ISSUE TITLE
YUV422 Interleaved to RGB conversion and then to JPEG

### ISSUE THREAD

**Issue by rajkn90** [CESNET/GPUJPEG#14]
Hi, 

I would like to convert "YUV422 Interleaved" format to RGB and then convert that to JPEG using this library. Where should I start, to add this function to convert YUV422 to RGB?

YUV422 Interleaved is explained in section 3.1.5 in http://www.ti.com/lit/an/sprab77a/sprab77a.pdf
It basically has separate Y channels for each pixel, but shared U and V channels between two pixels. I think this library expects 3 channels per pixel (correct me if I am wrong)

Thanks,
Keerthi

**Comment by MartinPulec** [comment]
Hi Keerthi,

I've checked the format and it looks like that format mentioned in section 3.1.5 of the document is simply GPUJPEG_422_U8_P1020 in GPUJPEG, therefore you may be able to use it directly.

Regards,
Martin

**Comment by rajkn90** [comment]
Thanks Martin. That works. However, I want to get the intermediate RGB output as well for other purposes. Is there any API in this library which can convert YUV422 interleaved to RGB?

**Comment by MartinPulec** [comment]
I'd just mention that there is no intermediate RGB if you encode YUV422 because GPUJPEG natively encodes YUV rather than RGB (JPEGs with RGB color components is quite rare). However, to your second question - modifying **gpujpeg_image_convert()** (or creating similar function) should work. If implemented like that, the conversion will be quite independent on the compression itself.
