### ISSUE TITLE
Is there GPUJPEG_BGR color space support?

### ISSUE THREAD

**Issue by rajkn90** [CESNET/GPUJPEG#17]
Hi, 

I have a BGR input image instead of RGB input. Can I set the color_space for jpeg encoding to be "GPUJPEG_BGR" instead of "GPUJPEG_RGB" ? If not, where should I start modifying to add support for BGR?

Right now if I pass BGR image and say it is "GPUJPEG_RGB", it compresses fine, but when I decompress it back, the colors are wrong when displayed. 

Thanks,
Keerthi

**Comment by rajkn90** [comment]
FYI - I am using a different decompressor - not from this library

**Comment by MartinPulec** [comment]
Hi Keerthi,

BGR is not currently supported. However, adding support may not require much time. I'll further suppose that you will have the JPEG internal representation in YCbCr (default). Then, these things need to be done:
1) add GPUJPEG_RGB colorspace (obviously), 
2) add specialization of `gpujpeg_color_transform<GPUJPEG_BGR, GPUJPEG_YCBCR_BT601_256LVLS>`. That should be, however, very similar to that with GPUJPEG_RGB because only channel order is changed.

As far as I know this should be sufficient - the colorspace transformation is done in the preprocessor (with the abovementioned template).

Martin

**Comment by rajkn90** [comment]
Thanks.
