### ISSUE TITLE
Distribution package requirements.

### ISSUE THREAD

**Issue by Sanich15** [CESNET/GPUJPEG#3]
On my machine, I've Installed the Cuda toolkit (version 8.0) to be able to build the gpujpeg project.
Now in my application I'm linking with the gpujpeb.lib and depending on gpujpeg.dll which on his place, depends on cudart_32_80.dll. So I guess that at least, I have to include those dlls in my package. Should I include something else?

And what about the system requirements? Of-course it should be with nvidia cuda enabled GPU. Something else?

Thanks!

**Comment by MartinPulec** [comment]
Hi,

exactly, you should include the mentioned DLL to be able to run. The 
NVIDIA license of CUDA runtime is quite permissive so usually there 
won't be a legal problem with redistribution. This is the only external 
dependency of GPUJPEG. As for system requirements - yep, in order to 
run, GPUJPEG requires CUDA device (with compute capability >= 2.0, which 
is any of recent NVIDIA GPUs). Of course assuming correctly installed 
drivers for NVIDIA. That should be all.


Regards,
Martin

**Comment by Sanich15** [comment]
@MartinPulec  Cool. And what about GPUJPEG license? I couldn't find the file...

**Comment by MartinPulec** [comment]
Well, yep, there is no license in the repo, however it is 2-clause BSD 
(also according to all source files).

Martin

**Comment by Sanich15** [comment]
Thanks!
