### ISSUE TITLE
GPUJPEG failed with DRI marker, added glfw in windows for gpujpeg_opengl_init 

### ISSUE THREAD

**Issue by Hubert-Yang** [CESNET/GPUJPEG#46]
Hi, 

I try to run GPUJPEG in windows with GLFW. the code only can compile with 32 bit in visual studio 2015. (64 bit Windows). The code failed with command line as:-d Hutton_in_the_Forest_4K.jpg output.yuv  --verbose -n 10 and result as: 

[GPUJPEG] [Error] gpujpeg_opengl_init not implemented in current OS!             <<<< this is warning since the library didn't implement windows, I manually add glfw for windows bypass it. 
CUDA driver version:   11.0
CUDA runtime version:  11.0
Using Device #0:       GeForce GTX 1660 SUPER (c.c. 7.5)
 
Decoding Image [Hutton_in_the_Forest_4K.jpg]
Load Image:                4.50 ms
[GPUJPEG] [Warning] JPEG data contains not supported APP1 marker
[GPUJPEG] [Warning] APP13 marker (segment info) scan index should be 0 but 80 was presented! (marker not a segment info?)
[GPUJPEG] [Warning] JPEG data contains not supported APP1 marker
[GPUJPEG] [Warning] JPEG data contains not supported APP2 marker
[GPUJPEG] [Error] DRI marker can't redefine restart interval (16 to 480)!
This may be caused when more DRI markers are presented which is not supported!          
[GPUJPEG] [Error] Decoder failed when decoding image data!
Failed to decode image [Hutton_in_the_Forest_4K.jpg]!
Press any key to continue . . .

The image is 3840x2160. Since it failed with line "DRI marker can't redefine restart interval", sounds this is for Linux. Is it possible fixed for Windows? 

Thanks

Hubert Yang

**Comment by MartinPulec** [comment]
Hi Hubert,

answering inline.

> I try to run GPUJPEG in windows with GLFW. the code only can compile with 32 bit in visual studio 2015. (64 bit Windows). 
> The code failed with command line as:-d Hutton_in_the_Forest_4K.jpg output.yuv --verbose -n 10 and result as:
> 
> [GPUJPEG] [Error] gpujpeg_opengl_init not implemented in current OS! <<<< this is warning since the library didn't implement windows, I manually add glfw for windows bypass it.

GPUJPEG can be easily compiled with provided CMake file (CMake is included with VS17+, see [here](https://docs.microsoft.com/en-us/cpp/build/cmake-projects-in-visual-studio?view=vs-2019)), moreover a prebuilt (64-bit) version is [here](https://github.com/CESNET/GPUJPEG/releases/tag/continuous).

You are correct that GPUJPEG doesn't implement OpenGL interoperability in Windows. Initializing GL context with GLFW may be a way to go. Just to be sure - are you using decoding to GL texture? Otherwise this is quite unneeded.

> CUDA driver version: 11.0
> CUDA runtime version: 11.0
> Using Device #0: GeForce GTX 1660 SUPER (c.c. 7.5)
> 
> Decoding Image [Hutton_in_the_Forest_4K.jpg]
> Load Image: 4.50 ms
> [GPUJPEG] [Warning] JPEG data contains not supported APP1 marker
> [GPUJPEG] [Warning] APP13 marker (segment info) scan index should be 0 but 80 was presented! (marker not a segment info?)
> [GPUJPEG] [Warning] JPEG data contains not supported APP1 marker
> [GPUJPEG] [Warning] JPEG data contains not supported APP2 marker
> [GPUJPEG] [Error] DRI marker can't redefine restart interval (16 to 480)!
> This may be caused when more DRI markers are presented which is not supported!
> [GPUJPEG] [Error] Decoder failed when decoding image data!
> Failed to decode image [Hutton_in_the_Forest_4K.jpg]!
> Press any key to continue . . .
> 
> The image is 3840x2160. Since it failed with line "DRI marker can't redefine restart interval", sounds this is for Linux. Is it possible fixed for Windows?

No, this doesn't have anything to do with Linux, DRI is a JPEG marker defining a restart interval. If you provide me the JPEG (and ideally also your code), I could tell you more. Basically GPUJPEG supports a subset of JPEG features, i.a. this is one of the restriction. If you provide me your file, I could tell if I can relax it or not

> 
> Thanks
> 
> Hubert Yang

Regards,
Martin

**Comment by Huiliang-Yang** [comment]
Hi Martin, 

Thanks for your reply, follow your suggestion, I managed to make the code working with another jpeg image in Windows 10. I still get some issue with inside gpujpeg_reader.c function gpujpeg_reader_read_sos: 
// We must init decoder before data is loaded into it
    if ( decoder->reader->comp_count == 0 ) {
        // Init decoder
       /* if ( gpujpeg_decoder_init(decoder, &decoder->reader->param, &decoder->reader->param_image) != 0 ) {
            return -1;
        }*/
    }
Here I comment out this reinit code then everything seems fine. I guess maybe that is my fault since I hack the code in main.c, add glfw inside and hard code image width and height. 

But in previous post, this DRI marker is really the part confused me and right now I can continue my work. Really appreciate your help. 

Regards, 

Hubert Yang

**Comment by MartinPulec** [comment]
Hi Hubert,

I am afraid that I cannot help you without the particular image - I would need to look at its properties since it is possible that there are some incompatible features.

Martin

**Comment by MartinPulec** [comment]
UPDATE: I've checked [this image](https://upload.wikimedia.org/wikipedia/commons/c/ce/Hutton_in_the_Forest_4K.jpg) that I've supposedly identified from your output and it decodes for me correctly with the command-line app.

The key is not to set any parameters or all - including restart interval, interleaving etc. which is quite difficult, eg. with this image it will result in something like `-i -r 480 -c ycbcr-jpeg -f 444-u8-p0p1p2 -s 3840x2160` while it is sufficient to simply execute:

    gpujpeg -d Hutton_in_the_Forest_4K.jpg Hutton_in_the_Forest_4K.rgb

This is quite counter-intuitive and I'll try to fix it somehow.

Martin

**Comment by MartinPulec** [comment]
You can also take a look at code in [MartinPulec/GPUJPEG](https://github.com/MartinPulec/GPUJPEG/). Changes there address some reconfiguration issues both in the library (which now allows reconfiguration) and app (which adds some more checks to initializes decoder only if user gives needed values explicitly). The changes will be merged soon.

**Comment by Huiliang-Yang** [comment]
Thanks, that is exactly the image that I used to test. I will check this MartinPulec/GPUJPEC branch.

**Comment by MartinPulec** [comment]
Hi @Hubert-Yang, did you manage to test that in the end?

Also, would you be wiling to provide the GLFW patch? I'd like to include it to GPUJPEG. If it is production-ready, you may also issue a pull request.

Thanks a lot,
Martin

**Comment by Hubert-Yang** [comment]
Hi,

I have been away from working on the project recently. But I really
appreciate your help.

Thanks

**Comment by MartinPulec** [comment]
Hi @Hubert-Yang, no problem, I'll keep the issue open yet for for a moment.

**Comment by MartinPulec** [comment]
GPUJPEG already has a support for GLFW context so I am closing this now.
