### ISSUE TITLE
GPUJPEG vs NVJPEG

### ISSUE THREAD

**Issue by wolfviking0** [CESNET/GPUJPEG#48]
Hi @MartinPulec  how are you ? 
I am back playing with JPEG over GPU, and I wanted to compare the timing between nvJPG and GPUJPEG

I first did a run using a complete random image, using various resolution from 512x512 to 8192x8192 in this case my timing its better using GPUJPEG:

```
GPU JPEG TOTAL TIME '8192' : 911.242 [ms]
NV JPEG TOTAL TIME '8192' : 1608.21 [ms]
```

But if I used a more standard JPG, a portrait face with uniform background the timing change to the opposite

```
GPU JPEG TOTAL TIME '8192' : 620.884 [ms]
NV JPEG TOTAL TIME '8192' : 441.444 [ms]
```

Do you have any idea why is that ? 

```
% ../install/bin/gpujpeg -I nvjpeg_encode_4096.jpg
GPUJPEG rev 2842002
width: 4096
height: 4096
component count: 3
color space: YCbCr BT.601 256 Levels (YCbCr JPEG)
internal representation: 444-u8-p012
segment count: 1

% ../install/bin/gpujpeg -I gpujpeg_encode_4096.jpg
GPUJPEG rev 2842002
width: 4096
height: 4096
component count: 3
color space: YCbCr BT.601 256 Levels (YCbCr JPEG)
internal representation: 444-u8-p012
segment count: 16384
```

**Comment by MartinPulec** [comment]
Hi Anthony,

> But if I used a more standard JPG,

I wouldn't say this – GPUJPEG produces very standard JPEGs, it is a baseline DCT-based, JFIF compatible image. If you mean the use of **restart interval**, it is a quite standard (part of the base definition). The non-standard thing here would be the use of **segment info marker** (`-g` option), which is GPUJPEG extension, but it must be enabled explicitly.

NVjpeg could, however, be able to profit from restart intervals as well, it is not a home-grown optimization (opposite to the segment info marker). 

To answer your question, I think that GPUJPEG is slower because when there is only _one segment_, it does the whole Huffman decoding on CPU. While the Huffman decoding process is actually sequential then (I wouldn't go into details why, ask if curious), it may be partly parallelized (either on GPU or CPU). The GPUJPEG's Huffman decoder is not optimized in this way because it is intended to be used mainly for "own" JPEGs.

But is is only my opinion - you can check the output of GPUJPEG sample application and see how much time does the Huffman decoding take, ideally compared to NVjpeg. You can also paste it here, if you want a feedback (or the actual image).

**Comment by wolfviking0** [comment]
Hi @MartinPulec  but for testing GPUJPEG I am using a JPG with segment :
```
segment count: 16384
```

So when I did the comparison, I use raw data then use the same api for encoding/decoding the jpg. 
The result from the binary gpu jpeg for decoding give, almost exactly the same result of my timing:

```
Decoding Image [gpujpeg_encode_8192.jpg]
Load Image:                1.68 ms
Decode Image GPU:         72.91 ms (only in-GPU processing)
Decode Image Bare:       588.26 ms (without copy to/from GPU memory)
Decode Image:            620.98 ms
Save Image:              479.73 ms
````

**Comment by MartinPulec** [comment]
Hi Anthony,

so you want to say that the decode time of GPUJPEG is higher even with _restart markers_ used?

Well, this may be possible, even though the difference is quite small. But the problem is that you are decoding a **single** image, where the initialization costs don't amortize well. What about if you iterate multiple times over the image (eg. `-n 4`)? I think that then there will be quite different values. I don't know how to do that for NVjpeg, but you can still use 4 copies (or 3 symlinks) to simulate that.

See [my results](https://github.com/CESNET/GPUJPEG/files/5230320/log.txt) for reference.

**Comment by wolfviking0** [comment]
Hi Martin,

Make sense, the initialization cost can be reduce, in my use case the resolution and image remain the same so I will be able to initialize the decoder just once.

I have more question, currently I would like to directly decode the jpg into my libtorch tensor.
My tensor has a structure RGB Planar 
[
  [R,R,R,R]
  [G,G,G,G]
  [B,B,B,B]
]

If I want to decode directly inside the tensor,  can I specify the GPU memory address for each plane ?
Also I potential need to add a step to normalize the value between -1 <-> 1 or 0 <-> 1 do you feel I can customize GPUJPEG to do such behavior ?
Currently my approach its different I am decoding the JPG then call a kernel to copy the image into the tensor and during the copy I am doing the normalization. I would like to remove the copy if possible.

Thanks

**Comment by MartinPulec** [comment]
Hi,

> If I want to decode directly inside the tensor, can I specify the GPU memory address for each plane ?

currently no, it will output directly to one buffer. But it may not be so hard to implement provided that you don't mind additional cudeMemcpy - the memcopies inside the GPU are quite fast. Just look [here](https://github.com/CESNET/GPUJPEG/blob/2842002b227be104d7ff69747da3fd5985f4683e/src/gpujpeg_decoder.c#L331).

> Also I potential need to add a step to normalize the value between -1 <-> 1 or 0 <-> 1 do you feel I can customize GPUJPEG to do such behavior ?
> Currently my approach its different I am decoding the JPG then call a kernel to copy the image into the tensor and during the copy I am doing the normalization. I would like to remove the copy if possible.

Well, my comment above perhaps answers that - the way you are doing this now is really the easiest.

But yes, I think that you may be able to implement it without memcpy, just look into the function [gpujpeg_preprocessor_decode()](https://github.com/CESNET/GPUJPEG/blob/2842002b227be104d7ff69747da3fd5985f4683e/src/gpujpeg_preprocessor.cu#L875) (well, it should be actually "postprocess"). What you need is to only to provide your kernel that will:
1. convert from YUV (assuming that the JPEG is YUV internally) - because you are replacing the kernel which does that
2. do the processing you need and store it to 3 buffers

The input format for your kernel will be subsampled YUV (RGB is also possible, but it is rather special case and JPEG needs to be encoded with internal RGB representation), I think it is possible to work with.

Or you can leave the postprocess kernel and just append your kernel after it.

On the other hand, in my humble opinion - I'd consider if it is worth doing, GPU memories are fast enough so the penalty of an additional memcpy is relatively small. Of course I don't know how critical the time is for you.
