### ISSUE TITLE
1920*1080 rgb to jpg spend 18-20ms 

### ISSUE THREAD

**Issue by whucj** [CESNET/GPUJPEG#62]
Hello.
I test "encode_raw_rgb" program in my pc. GPU P1000,CPU i7 2.60GHZ .
The result is  that 1920*1080 rgb to jpg spend 18-20ms .
Your experiment shows about 7-10ms.
![image](https://user-images.githubusercontent.com/15603414/117745617-67d9ac80-b23d-11eb-9b4b-ae617a53b437.png)

I want to know why the result occur? Thanks.

**Comment by MartinPulec** [comment]
The difference is most probably because the presented values represent a net computational time. The example you are mentioning is not a representative example how to achieve the best performance but rather a simple usage example.

There is a overhead of creating the encoder/decoder, initializing the device and allocating buffer. To see the times avoiding that, you can use the command-line application `gpujpeg` with the paramter `-n` giving number of iterations, let say 100 or so:

    ./gpujpeg -n 1000 -s 1920x1080 in.rgb out.jpg

**Comment by whucj** [comment]
Thanks @MartinPulec
