### ISSUE TITLE
Set restart_interval==8 the gpu can't  work

### ISSUE THREAD

**Issue by docache** [CESNET/GPUJPEG#69]
I set the  "decoder->reader->param.restart_interval = 8" then the gpu decode jpeg to rgb  with rgb error!

**Comment by MartinPulec** [comment]
Hi @docache, could you provide details according to our  [contributing guidelines](https://github.com/CESNET/GPUJPEG/blob/66d4732c21e7a48a59d1a74cd86de970d9745836/CONTRIBUTING.md#reporting-bugs)?

I don't know how/when you set the restart interval value but generally it is not tunable for the decoder, because the value is determined by the JPEG file. (It may be only pre-initialized).

**Comment by docache** [comment]
thank your answer.

I'm misunderstand the restart_interval meaning.
