### ISSUE TITLE
Merge decoder-gltex branch into master?

### ISSUE THREAD

**Issue by bailsman** [CESNET/GPUJPEG#7]
Is there a reason that decoder-gltex branch is maintained as a separate branch? The use of streams for encoding/decoding helps immensely when GPUJPEG is not the exclusive user of the GPU.

**Comment by MartinPulec** [comment]
Hi Emanuel,

actually there is not a special reason. The only reason is because the
decoder-gltex branch changed the API a bit and secondly it was not so
tested. However the intent is to merge it because the decoder-gltext
branch has more improvements over the master branch. However in master
there are some fixes not in decoder-gltex. Feel free to use decoder-
gltex for now, I'll perhaps merge those 2 branches soon, the API will
likely remain the same as in decoder-gltex. I can let you know when
done - there is no ETA, however because it has been already pending for
a while, I'd like to have it relatively soon


Regards,
Martin

-- 
Martin Pulec <pulec@cesnet.cz>
CESNET, z. s. p. o.

Emanuel Rietveld píše v Út 06. 03. 2018 v 07:06 -0800:

**Comment by bailsman** [comment]
Thank you for this wonderful software!
