### ISSUE TITLE
main.obj : error LNK2019: unresolved external symbol

### ISSUE THREAD

**Issue by wolfviking0** [CESNET/GPUJPEG#81]
Hi 

Building on windows it seems when using static library some of the executable failed to build with LNK2019

I have a big list of error similar to this one :
```
main.obj : error LNK2019: unresolved external symbol __imp_gpujpeg_decoder_get_image_info referenced in function main 
```

Here my cmake 

```
    PRECOMPILE(
        NAME
        gpujpeg
        URL
        https://github.com/CESNET/GPUJPEG.git
        CHECKOUT
        acbb8474558e25c0095b500b3f98f40920abf6b8
        FLAGS
        -DCMAKE_POSITION_INDEPENDENT_CODE=ON
        -DBUILD_OPENGL=OFF
        -DBUILD_SHARED_LIBS=OFF
        LIBRARIES
        gpujpeg
    )
```

**Comment by wolfviking0** [comment]
I think for this one something like that can be added to the cmake:

```
target_link_libraries(gpujpeg-bin gpujpeg)
if(NOT ${BUILD_SHARED_LIBS})
    set_target_properties(gpujpeg-bin PROPERTIES LINK_FLAGS "/WHOLEARCHIVE:gpujpeg")
endif()
```

Then it give another error : 

```
Severity | Code | Description | Project | File | Line | Suppression State
-- | -- | -- | -- | -- | -- | --
Error | LNK1149 | output filename matches input filename 'C:\Users\User\AppData\Roaming\starlabs\vega\windows\cmake\gpujpeg_acbb8474_windows_10.0.22000_AMD64_cuda11.6\build\Release\gpujpeg.lib' | gpujpeg-bin | C:\Users\User\AppData\Roaming\starlabs\vega\windows\cmake\gpujpeg_acbb8474_windows_10.0.22000_AMD64_cuda11.6\build\LINK | 1 |  
```

Maybe related to this line 
```
set_target_properties(gpujpeg-bin PROPERTIES OUTPUT_NAME "gpujpeg")
```

**Comment by wolfviking0** [comment]
At the end my patch look like that :
```
 target_link_libraries(gpujpeg-bin gpujpeg)
-set_target_properties(gpujpeg-bin PROPERTIES OUTPUT_NAME "gpujpeg")
+if(NOT ${BUILD_SHARED_LIBS} AND WIN32)
+    target_link_libraries(gpujpeg-bin PUBLIC $<LINK_LIBRARY:WHOLE_ARCHIVE,gpujpeg>)
+endif()
+if(NOT WIN32)
+    set_target_properties(gpujpeg-bin PROPERTIES OUTPUT_NAME "gpujpeg")
+endif()
```

**Comment by wolfviking0** [comment]
My final patch for this issue look like :
```
-target_link_libraries(gpujpeg-bin gpujpeg)
-set_target_properties(gpujpeg-bin PROPERTIES OUTPUT_NAME "gpujpeg")
+
+if(NOT ${BUILD_SHARED_LIBS} AND WIN32)
+    target_link_libraries(gpujpeg-bin PUBLIC $<LINK_LIBRARY:WHOLE_ARCHIVE,gpujpeg>)
+else()
+    target_link_libraries(gpujpeg-bin gpujpeg)
+endif()
+if(NOT WIN32)
+    set_target_properties(gpujpeg-bin PROPERTIES OUTPUT_NAME "gpujpeg")
+endif()
```

**Comment by MartinPulec** [comment]
I believe that easiest steps to reproduce is:

    cmake -DBUILD_SHARD_LIBS=OFF -Bbuild .
    cmake --build build

correct? I believe that it may be caused by the stuff like `__declspec(dllexport)` etc. in [gpujpeg_common.h](https://github.com/CESNET/GPUJPEG/blob/master/libgpujpeg/gpujpeg_common.h).

So I've tried to fix the issues in a bit different way, please look at the attached commits. For the easy part, I've set the name of the tool always as _gpujpegtool_.

For the upper part of your patch, I believe that a "correct" way is not to use _\_\_declspec(dllexport/dllimport)_ at all in static builds. I've seen that the common practice is to define `<LIBRARY>_STATIC` macro governing the use of declspecs, which is already used by GPUJPEG (_GPUJPEG\_STATIC_), It just needs to be set. AFAIK also library users needs to define that macro as well. I hope it will be included from within the generated CMake target file (_GPUJPEGConfig.cmake_ generated from [Config.cmake.in](https://github.com/CESNET/GPUJPEG/blob/master/Config.cmake.in)) but I am really unsure if it works that way and is the correct CMake way. What do you think?

**Comment by wolfviking0** [comment]
Thanks for your quick fix
