### ISSUE TITLE
can't decode correctly

### ISSUE THREAD

**Issue by redirus** [CESNET/GPUJPEG#9]
Hi, I used apis GPUJPEG provided to decode an image, here is the link

https://drive.google.com/open?id=1ptnJvrsInaaxvxT2n2o5COdeYswfZYtM

and I use opencv cv::Mat to store the image by pointer to decoding result and download it. here is the result

https://drive.google.com/open?id=1trYvm7nVZT6KgnkKJ2uAFSglUc101aRv

Most of images are fine using the api GPUJPEG provided.

Could you know what happened? Huffman decoding part or something else?

**Comment by redirus** [comment]
I tested the code and it did not work. The bug still exists

**Comment by redirus** [comment]
@MartinPulec 
I found that all images that can not be decoded rightly show:

[Error] Can't reinitialize decoder, implement if needed!

in code block
for ( int comp = 0; comp < param_image->comp_count; comp++ )
{
...
}
Var change will be 1.

Why did it happen?

**Comment by MartinPulec** [comment]
@redirus Okay, yet there was a problem - I pushed the revert to the GIT. Please use it (to work with the same code). Then, can you send me more steps to reproduce? Ideally using command-line application if it can be reproduced, if not, snippet of code exposing the problem.

But if it is the problem written in your later post, it looks rather as an intentional behavior. Looks like you are trying to decode image of different properties (perhaps size possibly also subsampling etc.) but the decoder is not intended to do so. You'd need to allocate separate decoder for different image sizes.

**Comment by MartinPulec** [comment]
Closed for inactivity.
